In [2]:
import numpy as np

In [4]:
mylist = [1, 2, 3]

In [5]:
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(2,4)

array([[0.8995178 , 0.41972325, 0.40953831, 0.54181542],
       [0.81910742, 0.49182407, 0.33195083, 0.6552466 ]])

In [33]:
np.random.randn(2,3) # Random normal distribution.

array([[ 0.82648269,  0.97257781, -1.12754333],
       [ 1.34091868, -0.54013246,  0.94209701]])

In [39]:
np.random.randint(0,101,(2,4))

array([[37, 62, 27, 46],
       [32, 71,  4, 92]])

In [41]:
np.random.seed(45)
np.random.rand(5)

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ])